version: "3.0"

services:
  worker:
    image: dockersamples/examplevotingapp_worker
    depends_on:
      - redis
      - db
    networks:
    - frontend
    - backend

  redis:
    image: redis:alpine
    volumes:
    - redis_db:/data
    networks:
    - frontend
    deploy:
      placement:
        constraints:
          - "node.hostname==server-3"

  vote:
    image: dockersamples/examplevotingapp_vote:before
    depends_on:
      - redis
    ports:
    - 5000:80
    networks:
    - frontend
    deploy:
      mode: replicated
      replicas: 3

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  result-app:
    image: dockersamples/examplevotingapp_result:before
    ports:
    - 5001:80
    networks:
      - backend
    depends_on:
      - db

volumes:
  postgres_db:
  redis_db:

networks:
  frontend:
  backend: